# -*- coding: utf-8 -*-
"""AI/ML_internship_task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cFoR3P1ZVMUTqJWOS8fwOAGmqAI_tFrJ

**Task2: Predict Future Stock Prices (Short-Term)**

Objective:
 Use historical stock data to predict the next day's closing price.
  
 Dataset:
 Stock market data from Yahoo Finance (retrieved using the yfinance Python library)
"""

import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

"""Loading Stock Data"""

df= yf.download('AAPL', start='2021-01-01',end='2025-01-01')
df.head(10)

"""**Prepareing Data**"""

df['Next_close'] = df['Close'].shift(-1)
X = df[['Open','High','Low','Volume']]
y = df['Next_close']
#dropping last row
df= df.dropna()

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, shuffle=False)
model= LinearRegression()
model.fit(X_train,y_train)

predictions = model.predict(X_test)

plt.figure(figsize=(12,6))
plt.plot(y_test.values, label='Actual')
plt.plot(predictions, label='Predicted')
plt.legend()
plt.title('Stock Price Prediction Actualvs Predicted Closing Price')
plt.xlabel('Time')
plt.ylabel('Price')
plt.show()

"""Model learned close relations between input features and closing price using Linear Regression.
Model can follow trends(general).
"""