# -*- coding: utf-8 -*-
"""AI/ML_internship_task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AcgnmaueTH6lA9n8BIfSfzCJt9K9zd_g

**Task 3: Heart Disease Prediction**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, roc_curve,auc

import kagglehub

# Download latest version
path = kagglehub.dataset_download("redwankarimsony/heart-disease-data")

print("Path to dataset files:", path)

import os
# Check files in folder
print(os.listdir(path))

df = pd.read_csv(os.path.join(path, 'heart_disease_uci.csv'))
df.head()

# Check missing values
print(df.isnull().sum())

df = df.dropna()

sns.countplot(x='thal', data=df)
plt.title("Heart Disease (1 = Yes, 0 = No)")
plt.show()

plt.figure(figsize=(10,8))
df['sex']= df['sex'].map({1:'Male', 0:'Female'})
sns.heatmap(df.select_dtypes(include=['number']).corr(), annot=True, cmap='coolwarm')
plt.show()

"""Preparing Data"""

df_encoded = pd.get_dummies(df, drop_first=True)
# The 'num' column represents the heart disease status. To make it a binary classification problem,
# we will classify 'num' > 0 as having heart disease (1) and 'num' == 0 as no heart disease (0).
y = (df_encoded['num'] > 0).astype(int)
X = df_encoded.drop('num', axis=1)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""Training Model"""

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix")
plt.show()

"""**Confusion Matrix** helps to understand the type of errors by model, 33True positive(correctly predicted), 2 Flase positive (incorrectly predicted), 3 False negative(incorrectly predicted Noheart diseases), 22 True positive(correctly predicted diseases)"""

y_prob = model.predict_proba(X_test)[:, 1]
fpr, tpr, _ = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

plt.plot(fpr, tpr, label="AUC = " + str(roc_auc))
plt.plot([0,1], [0,1], linestyle='--')
plt.legend()
plt.title("ROC Curve")
plt.show()

"""ROC curve and area under the curve(AUC):   roc_auc = 0.941."""

importance = pd.Series(model.coef_[0], index=X.columns)
importance.sort_values().plot(kind='barh')
plt.title("Feature Importance")
plt.show()

"""Binary heart diseases prediction task."""