# -*- coding: utf-8 -*-
"""AI/ML_internship_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xSW9DBxNxd95nXWOnGTmSOEW1DPoGP8h
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
#loading iris from seaborn
iris = sns.load_dataset('iris')
iris.head()

print("shape:", iris.shape)

print("cloumns:", iris.columns)

iris.info()

iris.describe()

"""Visualize the dataset"""

sns.scatterplot(x="sepal_length", y="sepal_width", hue="species", data=iris)
plt.title("Scatterplot of Sepal Length vs Sepal Width")
plt.show()

iris.hist(figsize=(10, 8))
plt.show()

"""Detect Outliers"""

plt.figure(figsize=(10, 6))
sns.boxplot(data=iris)
plt.show()

"""Description:
1. **Petal length** varies a lot showing inbig box.
2. **Petal Width** is smaller and moresimilar.
3. **Sepal** width has a few unusual values(dots/outliers)



"""